<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Edda Művek</title>
	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
    <header></header>
    <nav>
        <ul>
            <li>
                <a href="index.php">Kezdőlap</a>
            </li>
             <li>
                <a href="members.php">Tagok</a>
            </li>
             <li>
                <a href="album.php">Albumok</a>
            </li>
             <li>
                <a href="gallery.php">Galéria</a>
            </li>
        </ul>
    </nav>
    <main>
		<h1>Edda Művek</h1>
         <p>Az Edda Művek (1983-ig Edda Művek Miskolc, az 1985-től Edda Művek Magyarország) Magyarország egyik leghíresebb rockegyüttese. Az együttes magva 1973-ban alakult Griff néven, majd 1974-től Edda néven folytatták (ezt tekintjük a zenekar születési évének a „miskolci időszámítás” szerint, valamint ez év szeptemberében lett Pataky Attila az énekes). 1977-ben került a zenekarba Slamovits István, akinek a zenéje meghatározta a zenekar hangzásvilágát. A klasszikus „bakancsos” felállás 1978 szeptemberére állt össze, amikor Zselencz László is a zenekar tagja lett. 1980-tól lett Edda Művek a nevük, és ezt tekintjük a zenekar születési évének „országosan”. A zenekar nevében a „művek” szó azt szimbolizálja, hogy az együttes Miskolcon, egy tipikus északkelet-magyarországi iparvárosban – az „acélvárosban” – kezdte pályafutását. A lemezeladást nézve Magyarország egyik legsikeresebb rockcsapata lett. Szinte valamennyi lemezük "bearanyozódott". Ők voltak az elsők, akiknek vidéki létükre sikerült megtörniük a fővárosi zenekarok egyeduralmát.</p>
        <h2>Történet</h2>
        <h3>A kezdetek (1973-1977)</h3>
        <p>Két miskolci egyetemista, Halász József (zenekarvezető, dobok) és Ferenczi Zoltán (szólógitár) már 1972-ben megkíséreltek létrehozni egy együttest, de erre csak 1973-ban került sor, amikor létrejött a Griff, az Edda elődje. A zenekarnak nem volt kifejezett irányvonala, mindenféle zenét játszottak, amit csak a közönség hallani szeretett volna. Az egyetemi E/6-os kollégium próbatermében kezdtek el játszani, majd nemsokára az egyetemi Boci bárban (ma Rockwell Klub) léptek fel. A kollégium pincéjét próbateremnek rendezték be, a felszerelés nagy részét az egyetemi KISZ-szervezet kulturális bizottságától kapták. Népszerűségük hamar felfelé ívelt: bálokba, ötórai teákra, műsoros estekre hívták őket, és nemcsak a városban, hanem szerte Borsod-Abaúj-Zemplén megyében. Nem voltak hosszú távú terveik, mindössze az volt a céljuk, hogy az ösztöndíj mellé némi plusz jövedelmet szerezzenek. A zenekar harmadik állandó tagja Beély Katalin lett, Ferenczi Zoltán barátnője, aki korábban csak csellón játszott, itt viszont basszusgitáros lett.</p>
        <p>Néhány hónap elteltével úgy tűnt, hogy nem volt szerencsés a zenekar névválasztása. A három tag ekkor sorshúzással kívánt dönteni: a Griff mellett a Falatrax néven gondolkodtak, de Ferenczi Zoltán talált egy könyvet édesapjának a könyvei közt, melynek címe alapján lettek végül Edda. (Érdekesség, hogy Riskó Géza "Edda Művek" című könyvében a név eredetére egyéb magyarázatok is találhatóak. Beély Katalin azt mondta el itt, hogy Halász József apósának a könyvei közt volt, másutt pedig az szerepel, hogy Halász Józsefné Miklós Rózsa talált rá a nevezett könyvre egy antikváriumban). Edda névvel az óizlandi-germán irodalomnak két nagy fontosságú alkotását jelölik. Ezek mitológiai és hősi énekek, mondai dalok, de van köztük drámai párbeszéd és tanító darab is. A régebbi a verses Edda-dalok gyűjteménye, a másik az úgynevezett "ifjabb Edda", melyet Gábor Ignác fordított magyarra. A névválasztásból majdnem botrány lett, ugyanis a kulturális pártbizottságról „leszóltak”, hogy ezzel a névvel nem játszhatnak tovább, mivel Benito Mussolini lányát is így hívták. A vita úgy ért véget, hogy bemutatták az Edda-dalok című könyvet, s sikeresen érveltek az új nevük mellett.</p>
        <p>A megalakulást követően számtalan tagcsere volt, melyeket alig lehet nyomon követni. Első énekesük Zsiga Zoltán volt (tőle alkoholproblémái miatt váltak meg), majd Fodor Attila (Foci), kiválásával - bevonult katonának - pedig Pataky Attila. A Miskolci Egyetem E/6-os kollégiumának pincehelyiségében tartott meghallgatásán dőlt el, hogy beválasztják. Nem sokkal később egy billentyűssel bővültek, Fancsik Zoltán személyében, akit nem sokkal később Deák Ákos váltott. Pataky Attila kivételes személynek számított, aki a zenekarba kerülése után hamarosan húzóember lett a csapatban, és félbeszakadt sportpályafutása után - középtávfutó volt - élethivatásának tekintette a zenélést. Az ő biztatására a vidéki zenekarok közül az elsők között megszerezték az ORI-vizsgát, de még ekkor is hihetetlennek tűnt, hogy az Edda egyszer országosan ismert zenekar lehet. A záróvizsgákkal azonban az alapító tagok válaszút elé kerültek. A diplomához közeledve világossá vált, hogy nem bírják már a felgyorsult tempót, számukra véget ért az Edda. Beély Katalin, az együttes egyetlen női tagja később rádiós szerkesztő lett. 1974 őszén Halász József Zalaegerszegre költözött, de még előtte átadta Pataky Attilának a zenekar vezetését. A zenekar nevének tulajdonjoga feleségére szállt át, aki ezt később Patakynak adta át.</p>
        <p>1977-ig élénk zenészvándorlás volt az Eddánál. A zenekar tagjai voltak ebben az időszakban Szepcsik József (Sucu) dobos, Róna György basszusgitáros és Aranyosi György billentyűs. Pataky mellett rövid ideig egy másik énekes, Darázs István is tagja volt a csapatnak. Miután Szepcsik József bevonult katonának, a helyére Csapó György került a Reflexből. Csapó volt akkoriban az egyetlen ORI vizsgás zenész, ráadásul szintén Amati dobfelszerelésen játszott, mint Sucu. Szepcsik bevonult katonának, majd leszerelt, de nem tért vissza a csapathoz, mert két héttel később meghalt leukémiában. Elődje, Halász József szintén rákban hunyt el 1980-ban, az ő emlékére íródott 1985-ben az Emlékezni (egy régi jó barátra) című dal.</p>
        <h3>A „bakancsos” Edda (1977–1983)</h3>
        <p>1977-ben kereste fel Pataky a Budapesten albérletben élő Slamovits Istvánt, akinek épp akkor szűnt meg előző zenekara. Mindkettőjüknek határozott elképzelése volt, új útra lépnek, stílust váltanak, a kemény rock felé fordulnak. Ennek érdekében változtattak a néven is, innentől lettek Edda Művek. A miskolci zenekarokból kiválogatták a legjobb zenészeket, amolyan szupercsapatot hozva ezzel létre. Céljuk az országos siker elérése volt, ennek érdekében emberfeletti teljesítményt produkáltak. A budapesti bemutatkozás először nem volt sikeres (éppen egy Piramis-koncerttel egy időben léptek fel, így csak 178-an látták őket), de második nekifutásra már telt házas koncertet adtak.</p>
        <p>Első nagylemezük 1980 májusában jelent meg, és ezidáig több mint kétszázötvenezer példányban kelt el. A mai napig rendkívül népszerű, számai közül több sláger lett. Szerepeltek Almási Tamás "Ballagás" című filmjében, a második nagylemezük több száma filmzeneként is szolgált. A dorogi rockfesztiválon forgatták "A pártfogolt" című film egyes jeleneteit, melyben az Edda is kapott szerepet egy koncertbetét erejéig. A felállás stabilnak volt mondható, bár adódtak problémák (Barta Alfonz bevonulása katonának, majd disszidálása, Zselencz László egészségi állapota). Az első nagylemez sikere után Platina Turnét tartottak, amelyen fúvósokkal színesítették a hangzásvilágot. Ekkor turnézott velük először többek között Gömöry Zsolt is, aki szaxofonon játszott. Az 1982-es MIDEM fesztiválra korlátozott példányszámban kiadták Bad / The Roamer kislemezüket, mely két, angol nyelven rögzített felvételt (Bad [Rossz állapot] és The Roamer [A hűtlen]) tartalmazott. A lemez Magyarországon nem került forgalomba.</p>
        <p>1983-ban a Pataky és Slamovits közötti ellentétek odáig fajultak, hogy 1983. december 17-én búcsúkoncertet adtak. A szakítás oka, hogy míg Pataky ugyanazt szerette volna folytatni, amit eddig, Slamovits zeneileg többre vágyott. A gondokat tetézte, hogy harmadik nagylemezük anyagát a lemezgyár visszadobta, és egy szám kivételével ("Fekete élmény") az egészet újra kellett írni (később ezek a számok a Pataky–Slamovits lemezen megjelentek). A két zenész között a viszony elmérgesedett, és bár később többször is kibékültek, kapcsolatuk meglehetősen hűvösnek mondható.</p>
        <h3>Újrakezdés (1985–1993)</h3>
        <p>Pataky 1984-ben úgy döntött, hogy újraindítja az Eddát. Ehhez legelőször is tapasztalt zenészekkel kiutazott Norvégiába, ahol hónapokon keresztül "vendéglátóztak", azaz egy szórakozóhelyen zenéltek. A tempó feszített volt, nappal tanulták az új számokat, éjjel játszottak, de a régi Edda két megmaradt tagja, Pataky Attila és Fortuna László itt kezdték el kimunkálni az új hangzást. Az Edda Művek 1985-ben tért vissza Patakynál jó tíz évvel fiatalabb budapesti zenészekkel, így a miskolci mítosz némileg veszített erejéből. Fortuna betegség miatt nem tudta vállalni a további zenélést, így innentől kezdve számítható a Pataky-Gömöry páros zeneszerzői korszaka. Csak 1988-ra sikerült stabilizálni a felállást (főként gitárosposzton volt nagy a fluktuáció), és zeneileg is ekkor értek a csúcsra. Ekkor jelent meg a máig legerősebbnek tartott lemez, a Változó idők. Akkoriban több szokatlan helyszínen játszottak: például a Lenin Kohászati Művek acélszerkezeti csarnokában, vagy épp a márianosztrai börtönben. 1990-ben jubileumi koncertet tartottak Miskolcon, ahol fellépett az aktuális felállás mellett a "bakancsos" Edda, sőt a legelső felállás is. 1991-ben a két gitáros, Alapi István és Pethő Gábor Kanadába mentek (állításuk szerint azért hozták meg ezt a döntést, mert ekkor még mindig ideiglenesnek érezték a helyüket, és attól féltek, hogy visszajönnek a régiek), helyükre Kicska László (basszusgitár) és Kun Péter (gitár) került. Kun érkezésével a hangzás is keményedett, ugyanakkor éppen ebben az időszakban vettek fel egy unplugged anyagot a Magyar Televízió újonnan indított műsorában.</p>
        <p>Kun Péter azonban mindössze alig több mint két évig volt a zenekar tagja. 1993. július 10-én tisztázatlan körülmények között, közúti balesetben vesztette életét, éppen a hagyományos agárdi Edda-tábor alatt. Temetése után a zenekar romokban hevert, a folytatás is kétségessé vált a gyász miatt. Végül Alapi István visszatérésével újra stabilizálódott a zenekar. Kun emlékére íródott a csak rendkívüli alkalmakkor felcsendülő "Lelkünkből".</p>
        <h3>Ma (1993–)</h3>
        <p>1997-ben Hetényi Zoltán került Donászy Tibor helyére, azóta stabil a felállás. 1998-ban angol nyelvű albumot dobtak piacra (Fire and Rain). 1999-ben Pataky Attila szólókarrierbe is kezdett, melynek keretén belül mulatós nótákat, illetve világslágerek magyar feldolgozásait énekelte, melyek miatt sok kritikát, de elismerést is kapott.</p>
        <p>A XXI. századba lépve a zenekar hangzása is megváltozott némiképp. Hangsúlyos motívum lett az Edda részéről a magyarságtudat, illetve az ősök tisztelete, ezt a 2003-as "Örökség", illetve a 2005-ös "Isten az úton" alapozták meg. Ettől az időtől kezdve lett erősebb Pataky politikai szerepvállalása is. A régi hagyomány, az ötévente a klasszikus felállással (is) megrendezett jubileumi koncert is megszűnt, miután a 2000-es Kisstadion-beli koncerten történtek (Slamovits István a gázsi miatt keveredett vitába a többiekkel) miatt Pataky és Slamovits többé nem hajlandóak egymás jelenlétében egy színpadon lenni. 2006-ban a Sláger Rádió támogatásával megjelent "A szerelem hullámhosszán", a legnagyobb Edda-balladák újrahangszerelt változatait tartalmazó válogatásalbum. Körülbelül 5 évig tartó ígérgetés után 2008-ban megjelent az "Amíg él, el nem felejti" című első Edda-DVD, majd 2009-ben az "Átok és áldás" című album. Eközben Pataky is kiadta "Bor, szex, rock and roll... és lélek" című önéletrajzi könyvét.</p>
        <p>Az Edda Művek dallamos, gazdagon hangszerelt rockdalai és balladái főként a fiatalok társadalmi és érzelmi életével, mindennapi örömeivel, problémáival foglalkoznak, főként a kétezres években játszik jelentős szerepet dalszövegeikben az aktuálpolitika. Az együttes évente közel száz alkalommal lép fel országszerte, valamint a környező országok magyarlakta területein.</p>
    </main>
	<footer>
        <p>Hibák bejelentése <a href="">itt</a>.</p>
	</footer>

</body>
</html>